name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.1.3
  - pip=23.3.1
  - scipy=1.11.3
  - pytest=7.4.3
  - pip:
      - wandb==0.16.0
      - mlflow==2.8.1
