name: hyperparameter_tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=23.3.1
  - pandas=2.1.3
  - scikit-learn=1.3.2
  - hydra-core=1.3.2
  - optuna=3.4.0
  - pip:
      - wandb==0.16.0
      - mlflow==2.8.1
      - hydra-optuna-sweeper==1.2.0 