defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 123
    direction: minimize
    study_name: rf_optimization
    storage: null
    n_trials: 1
    n_jobs: 1
    params:
      modeling.random_forest.n_estimators: choice(50,100,200)
      modeling.random_forest.max_features: choice(0.1,0.33,0.5,0.75,1)

modeling:
  random_seed: 42
  val_size: 0.2
  stratify_by: "neighbourhood_group"
  max_tfidf_features: 10
  random_forest:
    n_estimators: 150
    max_depth: 25
    min_samples_split: 5
    min_samples_leaf: 1
    max_features: 0.45824
    n_jobs: -1
    criterion: squared_error
    oob_score: true
